name: CI

on: [push]

jobs:
  test:
    name: Run tests with coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: |
        git submodule init
        git submodule update --init
    - name: Install lcov
      run: sudo apt-get install -y lcov
    - name: CMake for Coverage
      run: cmake -DCMAKE_BUILD_TYPE=Coverage -H. -Bbuild
    - name: Build
      run: cmake --build build -- -j2
    - name: Run tests
      run: cmake --build build --target gtest_coverage
    - name: Send report to Codecov
      run: cd build/coverage && bash <(curl -s https://codecov.io/bash) -v || echo "Codecov did not collect coverage reports"
      if: success()
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  benchmark:
    if: github.ref == 'refs/heads/master'
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: |
        git submodule init
        git submodule update --init
    - name: CMake for Coverage
      run: cmake -DCMAKE_BUILD_TYPE=Release -H. -Bbuild
    - name: Build
      run: cmake --build build --target ben
    - name: Run
      run: ./build/ben --benchmark_format=json --benchmark_min_time=30 | tee ./benchmark_result.json
    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        tool: 'googlecpp'
        output-file-path: ./benchmark_result.json
        github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        # Push and deploy GitHub pages branch automatically
        auto-push: true

  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: |
        git submodule init
        git submodule update --init
    - name: CMake for Release
      run: cmake -DCMAKE_BUILD_TYPE=Release -H. -Bbuild
    - name: Build
      run: cmake --build build --target rst rst-debug
    - name: Test binary
      run: build/rst -h

    - name: Upload binary
      uses: actions/upload-artifact@master
      if: success()
      with:
        name: rst-${{ matrix.os }}
        path: build/rst
    - name: Upload debug binary
      uses: actions/upload-artifact@master
      if: success()
      with:
        name: rst-debug-${{ matrix.os }}
        path: build/rst-debug
